trigger: none
pr: none

schedules:
- cron: '0 0 * * *'
  displayName: Daily midnight build
  branches:
    include:
    - master
  always: true

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  displayName: 'Upgrade packages'
  inputs:
    targetType: 'inline'
    script: |
      for i in $(find . -type d -name 'Pulumi.FSharp.*' | grep -v 'Myriad\|Test\|Common')
      do
        PACKAGE=$(awk -F/ '{{split($2,a,"FSharp."); print a[1]a[2]}}' <<< $i)
        dotnet add $i package Pulumi.FSharp > /dev/null
        dotnet add $i package $PACKAGE > /dev/null
      done
      git config --global user.name "UnoSD"
      git config --global user.email "1582987+UnoSD@users.noreply.github.com"
      git add .
      git commit -m "Upgrade NuGet packages"