name: $(Rev:r)

# Set the pipeline variable `provider` to a provider E.G. `Azure` `AzureAD` `Aws` `Kubernetes`

# Create a secure file `Pulumi.FSharp.Extensions.vault.json`
# with the following content:
# {
#   "values": [
#     {
#       "secret": false,
#       "value": "<NuGet API key>",
#       "name": "nuGetApiKey"
#     }
#   ]
# }

trigger:
  branches:
    include:
      - master
  paths:
    include:
      - Pulumi.FSharp.Myriad/*

pool: #GitHubRunners
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: FakeVaultFile
  displayName: Download FAKE Vault file
  inputs:
    secureFile: Pulumi.FSharp.Extensions.vault.json

- task: DotNetCoreCLI@2
  displayName: Run FAKE
  env:
    FAKE_DETAILED_ERRORS: true
  inputs:
    command: run
    projects: ./Pulumi.FSharp.Build/Pulumi.FSharp.Build.fsproj
    arguments: -v:m