//------------------------------------------------------------------------------
//        This code was generated by myriad.
//        Changes to this file will be lost when the code is regenerated.
//------------------------------------------------------------------------------
[<AutoOpen>]
module Pulumi.FSharp.Azure.VirtualMachine

open Pulumi
open Pulumi.FSharp.Azure.Core
open Pulumi.Azure.Core
open Pulumi.FSharp
open Pulumi.Azure.Compute

type VirtualMachineBuilder() =
    inherit AzureResource()
    member _.Yield _ = AzureResource.Zero, VirtualMachineArgs()
    member _.Run(cargs, args: VirtualMachineArgs) = VirtualMachine(cargs.Name, args)

    [<CustomOperation("location")>]
    member _.Location((cargs, args: VirtualMachineArgs), location) =
        args.Location <- location
        cargs, args

let virtualMachine = VirtualMachineBuilder()
