module AzureLocations

// az account list-locations -o json | sed "s/$(az account show --query id -o tsv)/00000000-0000-0000-0000-000000000000/"
let locationsMap =
    Map.empty
    |> Map.add "eastus" "eastus"
    |> Map.add "East US" "eastus"
    |> Map.add "(US) East US" "eastus"
    |> Map.add "eastus2" "eastus2"
    |> Map.add "East US 2" "eastus2"
    |> Map.add "(US) East US 2" "eastus2"
    |> Map.add "southcentralus" "southcentralus"
    |> Map.add "South Central US" "southcentralus"
    |> Map.add "(US) South Central US" "southcentralus"
    |> Map.add "westus2" "westus2"
    |> Map.add "West US 2" "westus2"
    |> Map.add "(US) West US 2" "westus2"
    |> Map.add "westus3" "westus3"
    |> Map.add "West US 3" "westus3"
    |> Map.add "(US) West US 3" "westus3"
    |> Map.add "australiaeast" "australiaeast"
    |> Map.add "Australia East" "australiaeast"
    |> Map.add "(Asia Pacific) Australia East" "australiaeast"
    |> Map.add "southeastasia" "southeastasia"
    |> Map.add "Southeast Asia" "southeastasia"
    |> Map.add "(Asia Pacific) Southeast Asia" "southeastasia"
    |> Map.add "northeurope" "northeurope"
    |> Map.add "North Europe" "northeurope"
    |> Map.add "(Europe) North Europe" "northeurope"
    |> Map.add "swedencentral" "swedencentral"
    |> Map.add "Sweden Central" "swedencentral"
    |> Map.add "(Europe) Sweden Central" "swedencentral"
    |> Map.add "uksouth" "uksouth"
    |> Map.add "UK South" "uksouth"
    |> Map.add "(Europe) UK South" "uksouth"
    |> Map.add "westeurope" "westeurope"
    |> Map.add "West Europe" "westeurope"
    |> Map.add "(Europe) West Europe" "westeurope"
    |> Map.add "centralus" "centralus"
    |> Map.add "Central US" "centralus"
    |> Map.add "(US) Central US" "centralus"
    |> Map.add "northcentralus" "northcentralus"
    |> Map.add "North Central US" "northcentralus"
    |> Map.add "(US) North Central US" "northcentralus"
    |> Map.add "westus" "westus"
    |> Map.add "West US" "westus"
    |> Map.add "(US) West US" "westus"
    |> Map.add "southafricanorth" "southafricanorth"
    |> Map.add "South Africa North" "southafricanorth"
    |> Map.add "(Africa) South Africa North" "southafricanorth"
    |> Map.add "centralindia" "centralindia"
    |> Map.add "Central India" "centralindia"
    |> Map.add "(Asia Pacific) Central India" "centralindia"
    |> Map.add "eastasia" "eastasia"
    |> Map.add "East Asia" "eastasia"
    |> Map.add "(Asia Pacific) East Asia" "eastasia"
    |> Map.add "japaneast" "japaneast"
    |> Map.add "Japan East" "japaneast"
    |> Map.add "(Asia Pacific) Japan East" "japaneast"
    |> Map.add "jioindiawest" "jioindiawest"
    |> Map.add "Jio India West" "jioindiawest"
    |> Map.add "(Asia Pacific) Jio India West" "jioindiawest"
    |> Map.add "koreacentral" "koreacentral"
    |> Map.add "Korea Central" "koreacentral"
    |> Map.add "(Asia Pacific) Korea Central" "koreacentral"
    |> Map.add "canadacentral" "canadacentral"
    |> Map.add "Canada Central" "canadacentral"
    |> Map.add "(Canada) Canada Central" "canadacentral"
    |> Map.add "francecentral" "francecentral"
    |> Map.add "France Central" "francecentral"
    |> Map.add "(Europe) France Central" "francecentral"
    |> Map.add "germanywestcentral" "germanywestcentral"
    |> Map.add "Germany West Central" "germanywestcentral"
    |> Map.add "(Europe) Germany West Central" "germanywestcentral"
    |> Map.add "norwayeast" "norwayeast"
    |> Map.add "Norway East" "norwayeast"
    |> Map.add "(Europe) Norway East" "norwayeast"
    |> Map.add "switzerlandnorth" "switzerlandnorth"
    |> Map.add "Switzerland North" "switzerlandnorth"
    |> Map.add "(Europe) Switzerland North" "switzerlandnorth"
    |> Map.add "uaenorth" "uaenorth"
    |> Map.add "UAE North" "uaenorth"
    |> Map.add "(Middle East) UAE North" "uaenorth"
    |> Map.add "brazilsouth" "brazilsouth"
    |> Map.add "Brazil South" "brazilsouth"
    |> Map.add "(South America) Brazil South" "brazilsouth"
    |> Map.add "centralusstage" "centralusstage"
    |> Map.add "Central US (Stage)" "centralusstage"
    |> Map.add "(US) Central US (Stage)" "centralusstage"
    |> Map.add "eastusstage" "eastusstage"
    |> Map.add "East US (Stage)" "eastusstage"
    |> Map.add "(US) East US (Stage)" "eastusstage"
    |> Map.add "eastus2stage" "eastus2stage"
    |> Map.add "East US 2 (Stage)" "eastus2stage"
    |> Map.add "(US) East US 2 (Stage)" "eastus2stage"
    |> Map.add "northcentralusstage" "northcentralusstage"
    |> Map.add "North Central US (Stage)" "northcentralusstage"
    |> Map.add "(US) North Central US (Stage)" "northcentralusstage"
    |> Map.add "southcentralusstage" "southcentralusstage"
    |> Map.add "South Central US (Stage)" "southcentralusstage"
    |> Map.add "(US) South Central US (Stage)" "southcentralusstage"
    |> Map.add "westusstage" "westusstage"
    |> Map.add "West US (Stage)" "westusstage"
    |> Map.add "(US) West US (Stage)" "westusstage"
    |> Map.add "westus2stage" "westus2stage"
    |> Map.add "West US 2 (Stage)" "westus2stage"
    |> Map.add "(US) West US 2 (Stage)" "westus2stage"
    |> Map.add "asia" "asia"
    |> Map.add "Asia" "asia"
    |> Map.add "Asia" "asia"
    |> Map.add "asiapacific" "asiapacific"
    |> Map.add "Asia Pacific" "asiapacific"
    |> Map.add "Asia Pacific" "asiapacific"
    |> Map.add "australia" "australia"
    |> Map.add "Australia" "australia"
    |> Map.add "Australia" "australia"
    |> Map.add "brazil" "brazil"
    |> Map.add "Brazil" "brazil"
    |> Map.add "Brazil" "brazil"
    |> Map.add "canada" "canada"
    |> Map.add "Canada" "canada"
    |> Map.add "Canada" "canada"
    |> Map.add "europe" "europe"
    |> Map.add "Europe" "europe"
    |> Map.add "Europe" "europe"
    |> Map.add "france" "france"
    |> Map.add "France" "france"
    |> Map.add "France" "france"
    |> Map.add "germany" "germany"
    |> Map.add "Germany" "germany"
    |> Map.add "Germany" "germany"
    |> Map.add "global" "global"
    |> Map.add "Global" "global"
    |> Map.add "Global" "global"
    |> Map.add "india" "india"
    |> Map.add "India" "india"
    |> Map.add "India" "india"
    |> Map.add "japan" "japan"
    |> Map.add "Japan" "japan"
    |> Map.add "Japan" "japan"
    |> Map.add "korea" "korea"
    |> Map.add "Korea" "korea"
    |> Map.add "Korea" "korea"
    |> Map.add "norway" "norway"
    |> Map.add "Norway" "norway"
    |> Map.add "Norway" "norway"
    |> Map.add "southafrica" "southafrica"
    |> Map.add "South Africa" "southafrica"
    |> Map.add "South Africa" "southafrica"
    |> Map.add "switzerland" "switzerland"
    |> Map.add "Switzerland" "switzerland"
    |> Map.add "Switzerland" "switzerland"
    |> Map.add "uae" "uae"
    |> Map.add "United Arab Emirates" "uae"
    |> Map.add "United Arab Emirates" "uae"
    |> Map.add "uk" "uk"
    |> Map.add "United Kingdom" "uk"
    |> Map.add "United Kingdom" "uk"
    |> Map.add "unitedstates" "unitedstates"
    |> Map.add "United States" "unitedstates"
    |> Map.add "United States" "unitedstates"
    |> Map.add "eastasiastage" "eastasiastage"
    |> Map.add "East Asia (Stage)" "eastasiastage"
    |> Map.add "(Asia Pacific) East Asia (Stage)" "eastasiastage"
    |> Map.add "southeastasiastage" "southeastasiastage"
    |> Map.add "Southeast Asia (Stage)" "southeastasiastage"
    |> Map.add "(Asia Pacific) Southeast Asia (Stage)" "southeastasiastage"
    |> Map.add "centraluseuap" "centraluseuap"
    |> Map.add "Central US EUAP" "centraluseuap"
    |> Map.add "(US) Central US EUAP" "centraluseuap"
    |> Map.add "eastus2euap" "eastus2euap"
    |> Map.add "East US 2 EUAP" "eastus2euap"
    |> Map.add "(US) East US 2 EUAP" "eastus2euap"
    |> Map.add "westcentralus" "westcentralus"
    |> Map.add "West Central US" "westcentralus"
    |> Map.add "(US) West Central US" "westcentralus"
    |> Map.add "southafricawest" "southafricawest"
    |> Map.add "South Africa West" "southafricawest"
    |> Map.add "(Africa) South Africa West" "southafricawest"
    |> Map.add "australiacentral" "australiacentral"
    |> Map.add "Australia Central" "australiacentral"
    |> Map.add "(Asia Pacific) Australia Central" "australiacentral"
    |> Map.add "australiacentral2" "australiacentral2"
    |> Map.add "Australia Central 2" "australiacentral2"
    |> Map.add "(Asia Pacific) Australia Central 2" "australiacentral2"
    |> Map.add "australiasoutheast" "australiasoutheast"
    |> Map.add "Australia Southeast" "australiasoutheast"
    |> Map.add "(Asia Pacific) Australia Southeast" "australiasoutheast"
    |> Map.add "japanwest" "japanwest"
    |> Map.add "Japan West" "japanwest"
    |> Map.add "(Asia Pacific) Japan West" "japanwest"
    |> Map.add "jioindiacentral" "jioindiacentral"
    |> Map.add "Jio India Central" "jioindiacentral"
    |> Map.add "(Asia Pacific) Jio India Central" "jioindiacentral"
    |> Map.add "koreasouth" "koreasouth"
    |> Map.add "Korea South" "koreasouth"
    |> Map.add "(Asia Pacific) Korea South" "koreasouth"
    |> Map.add "southindia" "southindia"
    |> Map.add "South India" "southindia"
    |> Map.add "(Asia Pacific) South India" "southindia"
    |> Map.add "westindia" "westindia"
    |> Map.add "West India" "westindia"
    |> Map.add "(Asia Pacific) West India" "westindia"
    |> Map.add "canadaeast" "canadaeast"
    |> Map.add "Canada East" "canadaeast"
    |> Map.add "(Canada) Canada East" "canadaeast"
    |> Map.add "francesouth" "francesouth"
    |> Map.add "France South" "francesouth"
    |> Map.add "(Europe) France South" "francesouth"
    |> Map.add "germanynorth" "germanynorth"
    |> Map.add "Germany North" "germanynorth"
    |> Map.add "(Europe) Germany North" "germanynorth"
    |> Map.add "norwaywest" "norwaywest"
    |> Map.add "Norway West" "norwaywest"
    |> Map.add "(Europe) Norway West" "norwaywest"
    |> Map.add "switzerlandwest" "switzerlandwest"
    |> Map.add "Switzerland West" "switzerlandwest"
    |> Map.add "(Europe) Switzerland West" "switzerlandwest"
    |> Map.add "ukwest" "ukwest"
    |> Map.add "UK West" "ukwest"
    |> Map.add "(Europe) UK West" "ukwest"
    |> Map.add "uaecentral" "uaecentral"
    |> Map.add "UAE Central" "uaecentral"
    |> Map.add "(Middle East) UAE Central" "uaecentral"
    |> Map.add "brazilsoutheast" "brazilsoutheast"
    |> Map.add "Brazil Southeast" "brazilsoutheast"
    |> Map.add "(South America) Brazil Southeast" "brazilsoutheast"
